baseurl = "https://wbthomason.github.io/blog/"
languageCode = "en-us"
title = "something bloglike"
tagline = ""
theme = "lanyon"
MetaDataFormat = "yaml"
googleAnalytics = "UA-75724004-1"

[params]
  author = "Wil Thomason"
  title = "something bloglike"
  tagline = ""
  Github = "wbthomason"
  Twitter = "wilthomason"
  Linkedin = "wbthomason"
  Email = "wbthomason@{my department, abbr.}.{my university}.edu"
  DateForm = "02 Jan 2006"
