title = "something bloglike"
base_url = "https://wbthomason.github.io/blog"
compile_sass = true
highlight_code = true
highlight_theme = "gruvbox-light"
build_search_index = false
generate_feed = true
taxonomies = [{name = "tags", feed = true}]
[extra]
