name:                something-bloglike
version:             0.1.0.0
github:              "wbthomason/blog"
license:             MIT
author:              "Wil Thomason"
maintainer:          "wbthomason@cs.cornell.edu"
copyright:           "2020 Wil Thomason"

synopsis:            Wil Thomason's blog
category:            Slick-Site

description: Wil Thomason's blog, built with Slick

executables:
  build-site:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >= 4.7 && < 5
    - shake
    - directory
    - slick
    - text
    - containers
    - unordered-containers
    - pandoc
    - lens
    - aeson
    - lens-aeson
    - time
